#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Install packages
grep -v '^#' packages | xargs pkgin -y install

# copy files over
rsync -Pav copy/ /

# Prepare image for provisioning
sm-prepare-image -y
