#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Installing roundcube";
git -C /opt/local clone -b 1.1.4 https://github.com/roundcube/roundcubemail.git roundcube

mv /root/config.inc.php /opt/local/roundcube/config/config.inc.php
mv /root/managesieve.config.inc.php /opt/local/roundcube/plugins/managesieve/config.inc.php

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
